name: Benchmark
on:
  pull_request:
    branches:
      - master

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: 14
          cache: 'yarn'
          cache-dependency-path: 'k6/yarn.lock'

      - name: Use Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          working-directory: ./k6/graphql-api
          ruby-version: 2.6
          bundler-cache: true

      - name: Start GraphQL API with hive enabled
        working-directory: ./k6/graphql-api
        run: |
          bundle
          bundle exec puma -t 0:1 -p 9292 & sleep 5
        env:
          HIVE_ENABLED: 'true'

      - name: Start GraphQL API with hive disabled
        working-directory: ./k6/graphql-api
        run: |
          bundle
          bundle exec puma -t 0:1 -p 9291 & sleep 5
        env:
          HIVE_ENABLED: 'false'

      - name: Start Fake Usage API
        working-directory: ./k6/
        run: |
          yarn
          node usage-api.js & sleep 5s

      - name: Setup K6
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6=0.37.0

      - name: Start and Report Benchmark with Hive disabled
        working-directory: ./k6/graphql-api
        run: k6 -e GITHUB_PR=${{ github.event.number }} -e GITHUB_SHA=${{ github.sha }} -e GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}} run k6.js
